[profile]
name = "mister"
prefix = "games"

[platforms]
"nes"           = "NES"
"snes"          = "SNES"
"genesis"       = "Genesis"
"mega-drive"    = "MegaDrive"
"game-boy"      = "GAMEBOY"
"gba"           = "GBA"
"master-system" = "SMS"
"mega-cd"       = "MegaCD"
"n64"           = "N64"
"playstation"   = "PSX"
"saturn"        = "Saturn"
"tgfx16"        = "TGFX16"
"tgfx16-cd"     = "TGFX16-CD"
"neo-geo"       = "NeoGeo"
"atari-2600"    = "ATARI2600"
"atari-5200"    = "ATARI5200"
"atari-7800"    = "ATARI7800"
"game-gear"     = "SMS"
"s32x"          = "S32X"
"wonderswan"    = "WonderSwan"
"wonder-swan-color" = "WonderSwanColor"
"intellivision" = "Intellivision"
"colecovision"  = "Coleco"
"odyssey2"      = "ODYSSEY2"
"vectrex"       = "VECTREX"
"lynx"          = "AtariLynx"
"ngp"           = "NGP"
"ngpc"          = "NGPC"
"pokemon-mini"  = "PokemonMini"
