[profile]
name = "retroarch"

[platforms]
"nes"           = "nes"
"snes"          = "snes"
"genesis"       = "genesis"
"mega-drive"    = "megadrive"
"game-boy"      = "gb"
"gba"           = "gba"
"master-system" = "mastersystem"
"mega-cd"       = "segaCD"
"n64"           = "n64"
"playstation"   = "psx"
"saturn"        = "segaSaturn"
"tgfx16"        = "tg16"
"tgfx16-cd"     = "tg16cd"
"neo-geo"       = "neogeo"
"atari-2600"    = "atari2600"
"atari-5200"    = "atari5200"
"atari-7800"    = "atari7800"
"game-gear"     = "gamegear"
"s32x"          = "sega32x"
"wonderswan"    = "wonderswan"
"intellivision" = "intellivision"
"colecovision"  = "colecovision"
"lynx"          = "lynx"
